### ISSUE TITLE
Notice: Undefined property: stdClass::$media

### ISSUE THREAD

**Issue by anthonyhartnell** [AtomicSmash/twitter-feed-wordpress#1]
When pressing the "Sync" button in the admin, an error is producted for the 'media' column in the array:

`Notice: Undefined property: stdClass::$media in /home/vagrant/www/spikeisland.local/wp-content/plugins/twitter-feed-wordpress-master/twitter.php on line 408`

We should put in a check to see if it's not null before serialising.

**Comment by daviddarke** [comment]
@WebAssembler fixed
